# permissions for end users to view checkpointrestoreoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: checkpointrestoreoperator-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: checkpoint-restore-operator
    app.kubernetes.io/part-of: checkpoint-restore-operator
    app.kubernetes.io/managed-by: kustomize
  name: checkpointrestoreoperator-viewer-role
rules:
- apiGroups:
  - criu.org
  resources:
  - checkpointrestoreoperators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - criu.org
  resources:
  - checkpointrestoreoperators/status
  verbs:
  - get
