apiVersion: criu.org/v1
kind: CheckpointRestoreOperator
metadata:
  labels:
    app.kubernetes.io/name: checkpointrestoreoperator
    app.kubernetes.io/instance: checkpointrestoreoperator-sample
    app.kubernetes.io/part-of: checkpoint-restore-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: checkpoint-restore-operator
  name: checkpointrestoreoperator-sample
spec:
  checkpointDirectory: /var/lib/kubelet/checkpoints
  applyPoliciesImmediately: false
  globalPolicy:
    maxCheckpointsPerNamespace: 50
    maxCheckpointsPerPod: 30
    maxCheckpointsPerContainer: 10
  # containerPolicies:
  #   - namespace: namespace
  #     pod: pod_name
  #     container: container_name
  #     maxCheckpoints: 5
  # podPolicies:
  #   - namespace: namespace
  #     pod: pod_name
  #     maxCheckpoints: 10
  # namespacePolicies:
  #   - namespace: namespace
  #     maxCheckpoints: 15