on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      CHECKPOINT_DIR: /var/lib/kubelet/checkpoints
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Install dependencies
        run: |
          # Install kind
          curl -sLo kind "$(curl -sL https://api.github.com/repos/kubernetes-sigs/kind/releases/latest | jq -r '[.assets[] | select(.name == "kind-linux-amd64")] | first | .browser_download_url')"
          chmod +x kind
          sudo mv kind /bin/
          
          # Install kubectl
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /bin/

      - name: Prepare Checkpoints Directory in Host
        run: |
          sudo mkdir -p ${{ env.CHECKPOINT_DIR }}
          sudo chmod 700 ${{ env.CHECKPOINT_DIR }}
          sudo chown $USER ${{ env.CHECKPOINT_DIR }}
          # sudo echo ${{ env.CHECKPOINT_DIR }}

      - name: Generate Checkpoint Tar Files
        run: ./test/generate_checkpoint_tar.sh

      # - name: Generate Kind Config
      #   run: ./test/generate_kind_config.sh

      # - name: Delete Existing Kind Cluster
      #   run: kind delete cluster || true

      - name: Create Kubernetes cluster
        run: kind create cluster --config=./test/kind-config.yaml

      - name: Load Docker image into kind cluster
        run: |
          # docker rmi checkpoint-restore-operator:ci || true
          make docker-build IMG=checkpoint-restore-operator:ci
          # docker images | grep checkpoint-restore-operator
          kind load docker-image checkpoint-restore-operator:ci

      # - name: Replace Placeholder in Manager
      #   run: |
      #     sed -i "s#__CHECKPOINT_DIR__#${{ env.CHECKPOINT_DIR }}#g" ./config/manager/manager.yaml

      - name: Deploy to Kubernetes
        run: |
          make install
          make deploy IMG=checkpoint-restore-operator:ci
          sudo ls ${{ env.CHECKPOINT_DIR }}

      - name: Wait for deployments to be ready
        run: ./test/wait_for_deployment.sh checkpoint-restore-operator-controller-manager

      - name: Check resources
        run: kubectl get all -n checkpoint-restore-operator-system

      - name: Wait for Checkpoint Tar Files to Reduce to 2
        run: |
          ls -la ${{ env.CHECKPOINT_DIR }}

          # Checkpoint files should reduced to 2
          kubectl apply -f ./test/test_checkpointrestoreoperator.yaml
          ./test/wait_for_checkpoint_reduction.sh 2
          ls -la ${{ env.CHECKPOINT_DIR }}

      - name: Wait for Checkpoint Tar Files to Reduce to 7
        run: |
          # Checkpoint files should not reduced to 0
          ./test/generate_checkpoint_tar.sh
          sed -i 's/maxCheckpointsPerContainer: [0-9]*/maxCheckpointsPerContainer: 0/' ./test/test_checkpointrestoreoperator.yaml
          sed -i '/^  containerPolicies:/,/maxCheckpoints: [0-9]*/ s/^/#/' ./test/test_checkpointrestoreoperator.yaml
          cat ./test/test_checkpointrestoreoperator.yaml
          ls -la ${{ env.CHECKPOINT_DIR }}
          kubectl apply -f ./test/test_checkpointrestoreoperator.yaml
          ./test/wait_for_checkpoint_reduction.sh 7
          ls -la ${{ env.CHECKPOINT_DIR }}

      - name: Wait for Checkpoint Tar Files to Reduce to 1
        run: |
          # Checkpoint files should reduced to 1
          sed -i 's/maxCheckpointsPerContainer: [0-9]*/maxCheckpointsPerContainer: 1/' ./test/test_checkpointrestoreoperator.yaml
          sed -i '/^  containerPolicies:/,/maxCheckpoints: [0-9]*/ s/^/#/' ./test/test_checkpointrestoreoperator.yaml
          cat ./test/test_checkpointrestoreoperator.yaml
          kubectl apply -f ./test/test_checkpointrestoreoperator.yaml
          ./test/wait_for_checkpoint_reduction.sh 1
          ls -la ${{ env.CHECKPOINT_DIR }}
