on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Install dependencies
        run: |
          # Install kind
          curl -sLo kind "$(curl -sL https://api.github.com/repos/kubernetes-sigs/kind/releases/latest | jq -r '[.assets[] | select(.name == "kind-linux-amd64")] | first | .browser_download_url')"
          chmod +x kind
          sudo mv kind /bin/
          
          # Install kubectl
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /bin/

      - name: Prepare Checkpoints Directory in Host
        run: |
          sudo mkdir -p /var/lib/kubelet/checkpoints
          sudo chmod 777 /var/lib/kubelet/checkpoints

#       - name: Testing on a k8s Kind Cluster
#         uses: helm/kind-action@v1.4.0
# ## makes sure cluster is up and running
#       - run: |
#           kubectl cluster-info
#           kubectl get nodes

      - name: Generate Checkpoint Tar Files
        run: ./test/generate_checkpoint_tar.sh

      - name: Generate Kind Config
        run: ./test/generate_kind_config.sh

      - name: Delete Existing Kind Cluster
        run: kind delete cluster || true

      - name: Create Kubernetes cluster
        run: kind create cluster --config=kind-config.yaml

      - name: Load Docker image into kind cluster
        run: |
          docker rmi checkpoint-restore-operator:ci || true
          make docker-build IMG=checkpoint-restore-operator:ci
          docker images | grep checkpoint-restore-operator
          kind load docker-image checkpoint-restore-operator:ci

      - name: Deploy to Kubernetes
        run: |
          make install
          make deploy IMG=checkpoint-restore-operator:ci
          sudo ls /var/lib/kubelet/checkpoints

      - name: Wait for deployments to be ready
        run: ./test/wait_for_deployment.sh checkpoint-restore-operator-controller-manager

      - name: Check resources
        run: kubectl get all -n checkpoint-restore-operator-system

      # - name: Check mounted directory
      #   run: |
      #     POD_NAME=$(kubectl get pods -n checkpoint-restore-operator-system -l control-plane=controller-manager -o jsonpath='{.items[0].metadata.name}')
      #     kubectl exec -it $POD_NAME -n checkpoint-restore-operator-system --container manager -- bash -c "ls -l /var/lib/kubelet/checkpoints"

      - name: Wait for Checkpoint Tar Files to Reduce
        run: |
          kubectl apply -f ./test/test_checkpointrestoreoperator.yaml
          ./test/wait_for_checkpoint_reduction.sh