name: verify

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          only-new-issues: true
          args: --timeout=5m
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: codespell
        uses: codespell-project/actions-codespell@v2
        with:
          skip: vendor,*.svg

  gomod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: verify go.mod/go.sum
        run: |
          make vendor
          git diff --exit-code

  lint_markdown:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          base: 'main'  
          filters: |
            md:
              - 'README.md'
              - '.github/workflows/verify.yml'

      - name: Lint markdown
        if: steps.changes.outputs.md == 'true'
        uses: DavidAnson/markdownlint-cli2-action@v10
        with:
          globs: |
            README.md
